# Assignment 12
# Md. Shariar Imroze Khan
# Matriculation Number: 220202354

In [1]:
import numpy as np
import pandas as pd

class Eval:
    TP = 0
    FP = 0
    FN = 0
    TN = 0
     
    # parameterized constructor
    def __init__(self, ground, predicted):
        self.g = ground
        self.p = predicted
        self.conf_mat = np.array([self.g, self.p])
        self.TP = np.diag(self.conf_mat)
        self.FP = np.sum(self.conf_mat, axis=0) - self.TP
        self.FN = np.sum(self.conf_mat, axis=1) - self.TP
        self.TN = self.conf_mat.sum() - (self.FP + self.FN + self.TP)
   
 
    def getPrecision(self):
        self.Precision = self.TP/(self.TP+self.FP) * 100
    
    def getRecall(self):
        self.Recall = self.TP/(self.TP+self.FN) * 100
        
    def getAccuracy(self):
        self.Accuracy = (self.TP+self.TN)/(self.TP+self.TN+self.FP+self.FN) * 100
    
    def getF1Score(self):
        self.F1Score = self.TP/(self.TP+(0.5*(self.FP+self.FN))) * 100
        
    def printEval(self):
        print("Confusion matrix  \n " + str(self.conf_mat))
        
        
        
        df = pd.DataFrame(self.Precision, columns = ['Precision'])
        df.insert(1, "Recall", self.Recall, True)
        df.insert(2, "Accuracy", self.Accuracy, True)
        df.insert(3, "F1Score", self.F1Score, True)
    
        print("\n", df)
       
        




In [2]:
# array of actual values
ground = [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

# array of predicted values
predicted = [0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]

ground = pd.Series(ground, name='Actual')
predicted = pd.Series(predicted, name='Predicted')

#create confusion matrix
df = pd.crosstab(ground, predicted)

df

Predicted  0  1
Actual         
0          2  5
1          4  9

In [3]:
ground, predicted = df.to_numpy()

In [4]:
ground

array([2, 5], dtype=int64)

In [5]:
predicted

array([4, 9], dtype=int64)

In [6]:
# creating object of the class
# this will invoke parameterized constructor

calc = Eval(ground, predicted)
 
# perform Addition
calc.getPrecision()
calc.getRecall()
calc.getAccuracy()
calc.getF1Score()

# display result
calc.printEval()

Confusion matrix  
 [[2 5]
 [4 9]]

    Precision     Recall  Accuracy    F1Score
0  33.333333  28.571429      55.0  30.769231
1  64.285714  69.230769      55.0  66.666667
