In [1]:
import numpy as np
x = np.matrix([[440, 1], 
               [448,1],
               [6205,1],
               [4850,1],
               [1420,1],
               [16500,1],
               [1776,1],
               [6989,1],
               [2040,1],
               [9356,1]])
y = np.matrix([[123], 
               [137],
               [409],
               [459],
               [89],
               [1067],
               [230],
               [496],
               [208],
               [652]])

In [2]:
x_transpose = x.transpose()
x_transpose

matrix([[  440,   448,  6205,  4850,  1420, 16500,  1776,  6989,  2040,
          9356],
        [    1,     1,     1,     1,     1,     1,     1,     1,     1,
             1]])

In [3]:
one = np.dot(x_transpose,x)
one

matrix([[480381862,     50024],
        [    50024,        10]])

In [4]:
two = np.dot(x_transpose,y)
two

matrix([[33010827],
        [    3870]])

In [5]:
three = np.dot(np.linalg.inv(one),two)
three

matrix([[5.93179455e-02],
        [9.02679097e+01]])

In [6]:
inverse=np.linalg.inv(one)
inverse

matrix([[ 4.34514713e-09, -2.17361640e-05],
        [-2.17361640e-05,  2.08732987e-01]])

In [7]:
g_berlin = 5.93179455e-02 * 440  + 9.02679097e+01
g_moscow = 5.93179455e-02 * 2040 + 9.02679097e+01
g_kyiv = 5.93179455e-02 * 1591 + 9.02679097e+01

print("Berlin,Moscow,Kyiv: ", g_berlin,g_moscow,g_kyiv)

Berlin,Moscow,Kyiv:  116.36780572 211.27651852 184.6427609905


In [8]:
MSE = 1/3*((138-g_kyiv)**2+(123-g_berlin)**2+(208-g_moscow)**2)
MSE

743.4229091321583