In [1]:
import pandas as pd 
import numpy as np

x = np.array([56,100,23,480,32])
mean_x = np.mean(x)
n = len(x)
SD = np.std(x)

z_score = np.array((x[0:n]-mean_x)/SD)
z_score

array([-0.4752274 , -0.22084777, -0.66601212,  1.97606722, -0.61397993])

In [2]:
import pandas as pd 
import numpy as np

y = np.array([300,10,234])
mean_y = np.mean(y)
n_1 = len(y)
SD_1 = np.array(((y[0:n_1]-mean_y)**2)/(n_1-1))

z_score_1 = np.array((y[0:n_1]-mean_y)/SD_1)
z_score_1

array([ 0.01685393, -0.01167315,  0.03797468])

In [6]:
import numpy as np

H = [5.4,5.6,4.8,5.11]
W = [52,58.5,42.6,60]
A = [21,26,23,29]

data = np.array([H,W,A])

covMatrix = np.cov(data)
print(covMatrix)

[[1.21691667e-01 1.83325000e+00 2.25000000e-02]
 [1.83325000e+00 6.27025000e+01 1.95250000e+01]
 [2.25000000e-02 1.95250000e+01 1.22500000e+01]]


In [20]:
#Compute the eigen values for the below matrix M
import numpy as np
from numpy import linalg as la

M = np.array([[5,-3],[-6,2]])
w,v = la.eig(M)
print("Eigen values", w)
print("Eigen vectors", v)

Eigen values [ 8. -1.]
Eigen vectors [[ 0.70710678  0.4472136 ]
 [-0.70710678  0.89442719]]


In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv("iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]